name: add-issue-to-projects-beta
description: 'Adds content to project boards (beta)'
inputs:
  project-number:
    description: 'Project number'
    required: true
  project-owner:
    description: 'Project owner (user or organization)'
    required: true
  github-token:
    description: 'GitHub PAT with private repo or org access'
    required: true
outputs:
  project-item-id:
    description: 'The ID of the content added to the project board'
runs:
  using: 'node16'
  main: 'dist/index.js'
